name: Ruby

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.0']

    steps:
    - name: Checkout to get spec files
      uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      # with:
      #   ruby-version: 3.2.1
      #   bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Set up Ruby2
      run: |
        bundle lock --add-platform x86_64-linux
        bundle exec rspec
